version: '3.8'

services:
  backend:
    build:
      context: ./backend
    restart: unless-stopped
    entrypoint: ["bash", "Scripts/run_backend.sh"]
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - database
  database:
    image: postgres
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - mobicult_trial_db:/var/lib/postgresql/data
  updater:
    build:
      context: ./backend
    restart: unless-stopped
    entrypoint: ["python", "-m", "Scripts.loader_task"]
    env_file:
      - ./.env
    depends_on:
      - database
volumes:
  mobicult_trial_db: