"""alter models

Revision ID: 63a9c7558952
Revises: 653d7819b080
Create Date: 2023-11-16 16:24:44.647620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63a9c7558952'
down_revision: Union[str, None] = '653d7819b080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency_values', sa.Column('date', sa.DATE(), nullable=False))
    op.drop_column('currency_values', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency_values', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('currency_values', 'date')
    # ### end Alembic commands ###
