"""add nullable params

Revision ID: 653d7819b080
Revises: 853110cf8b28
Create Date: 2023-11-16 16:15:12.770244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '653d7819b080'
down_revision: Union[str, None] = '853110cf8b28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('currencies', 'cbr_id',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('currencies', 'char_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('currency_values', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('currency_values', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('currencies', 'char_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('currencies', 'cbr_id',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###
