"""expand currency model

Revision ID: 853110cf8b28
Revises: 8bf1f4d521e9
Create Date: 2023-11-16 16:11:34.773487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '853110cf8b28'
down_revision: Union[str, None] = '8bf1f4d521e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currencies', sa.Column('cbr_id', sa.String(length=10), nullable=True))
    op.add_column('currencies', sa.Column('char_code', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currencies', 'char_code')
    op.drop_column('currencies', 'cbr_id')
    # ### end Alembic commands ###
